### ISSUE TITLE
Bugs in sample learners?

### ISSUE THREAD

**Issue by act65** [facebookresearch/CommAI-env#24]
I get this when I run any/all of the sample learners. It answers a few questions, does pretty crap and then half way through it throws this error. (el capitan, anaconda 3.5, ?)

```
Traceback (most recent call last):
  File "run.py", line 191, in <module>
    main()
  File "run.py", line 83, in main
    session.run()
  File "/Volumes/ExtraDiskSpace/Documents/CommAI-env/src/core/session.py", line 52, in run
    token, reward = self._env.next(token)
  File "/Volumes/ExtraDiskSpace/Documents/CommAI-env/src/core/environment.py", line 113, in next
    self._switch_new_task()
  File "/Volumes/ExtraDiskSpace/Documents/CommAI-env/src/core/environment.py", line 279, in _switch_new_task
    self._current_task.start(self)
  File "/Volumes/ExtraDiskSpace/Documents/CommAI-env/src/core/task.py", line 451, in start
    self._env.raise_event(Start())
  File "/Volumes/ExtraDiskSpace/Documents/CommAI-env/src/core/environment.py", line 212, in raise_event
    return self.event_manager.raise_event(event)
  File "/Volumes/ExtraDiskSpace/Documents/CommAI-env/src/core/events.py", line 70, in raise_event
    trigger.event_handler(observer, event)
  File "/Volumes/ExtraDiskSpace/Documents/CommAI-env/src/tasks/competition/navigation.py", line 589, in on_start
    pe(np, objects[self.dir2obj[i]], True, True)
TypeError: 'set' object does not support indexing```

Also, I tried the human-mode and couldn't get any reward. Am I just being stupid?

**Comment by Timopheym** [comment]
@act65 what command are you using to run CommAI?
I have os x Yosemite, it works fine.
```
tim@Timopheys-MacBook-Pro ~/P/a/C/src> uname -a
Darwin Timopheys-MacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
tim@Timopheys-MacBook-Pro ~/P/a/C/src> python3 run.py -l learners.sample_learners.SampleRepeatingLearner -v ConsoleView tasks_config.json
*Start console view*
tim@Timopheys-MacBook-Pro ~/P/a/C/src> python3 --version
Python 3.5.0

**Comment by act65** [comment]
From running `python run.py tasks_config.json --learner=learners.sample_learners.SampleSilentLearner`

I get the same error on linux with py2.7.
The error is irregular, I havent noticed any patterns in when it breaks...

**Comment by Timopheym** [comment]
Thanks @act65! I found the problem and can reproduce it.
There is a trying to get value from set object ```objects``` there have to be changed logic due going throw the ```objects```. 

It's in ```FindObjectAroundTask``` for workaround you just need to remove  ```aj3``` task from scheduler.args.tasks in ```tasks_config.json```.

**Comment by ajabri** [comment]
Yes, I think in some python3 compatibility refactoring that bug got in there.

**Comment by Timopheym** [comment]
@ajabri don't think so.. FindObjectAroundTask was added after pyhon3 fixes.
Really i can't understand how did you want to get object by direction? Indexing does not work with sets...

**Comment by ajabri** [comment]
It's actually from when the find object tasks were incorrectly merged into the navigation tasks. This is now fixed.
