### ISSUE TITLE
Run test fail.

### ISSUE THREAD

**Issue by andreamad8** [facebookresearch/CommAI-env#39]
Hi, 

I am trying to run the tests by running under the src folder: 

`python -m unittest discover`

but I receive the following error:

```
======================================================================
ERROR: testTask11 (tasks.micro.tests.test_nano.TestRepetitionTasks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/samurai/Documents/HKUST/CommAI-env/src/tasks/micro/tests/test_nano.py", line 103, in testTask11
    correct=True)
  File "/Users/samurai/Documents/HKUST/CommAI-env/src/tasks/micro/tests/test_nano.py", line 26, in trySolution
    serializer=IdentitySerializer()) as m:
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/samurai/Documents/HKUST/CommAI-env/src/tasks/competition/tests/helpers.py", line 156, in task_messenger
    m = EnvironmentMessenger(env, serializer)
  File "/Users/samurai/Documents/HKUST/CommAI-env/src/tasks/competition/tests/helpers.py", line 26, in __init__
    self.init()
  File "/Users/samurai/Documents/HKUST/CommAI-env/src/tasks/competition/tests/helpers.py", line 30, in init
    first_bit, reward = self._env.next(None)
  File "/Users/samurai/Documents/HKUST/CommAI-env/src/core/environment.py", line 92, in next
    self._switch_new_task(train_mode=not(test_mode))
  File "/Users/samurai/Documents/HKUST/CommAI-env/src/core/environment.py", line 257, in _switch_new_task
    self._current_task = self._task_scheduler.get_next_task(train_mode=train_mode)
TypeError: get_next_task() got an unexpected keyword argument 'train_mode'

======================================================================
ERROR: testReverseXTask (tasks.micro.tests.test_small_comp.TestSmallCompTasks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/samurai/Documents/HKUST/CommAI-env/src/tasks/micro/tests/test_small_comp.py", line 53, in testReverseXTask
    self._test_solution(small_comp.ReverseXTask, get_correct_answer, True)
  File "/Users/samurai/Documents/HKUST/CommAI-env/src/tasks/micro/tests/test_small_comp.py", line 20, in _test_solution
    serializer=IdentitySerializer()) as m:
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/samurai/Documents/HKUST/CommAI-env/src/tasks/competition/tests/helpers.py", line 156, in task_messenger
    m = EnvironmentMessenger(env, serializer)
  File "/Users/samurai/Documents/HKUST/CommAI-env/src/tasks/competition/tests/helpers.py", line 26, in __init__
    self.init()
  File "/Users/samurai/Documents/HKUST/CommAI-env/src/tasks/competition/tests/helpers.py", line 30, in init
    first_bit, reward = self._env.next(None)
  File "/Users/samurai/Documents/HKUST/CommAI-env/src/core/environment.py", line 92, in next
    self._switch_new_task(train_mode=not(test_mode))
  File "/Users/samurai/Documents/HKUST/CommAI-env/src/core/environment.py", line 257, in _switch_new_task
    self._current_task = self._task_scheduler.get_next_task(train_mode=train_mode)
TypeError: get_next_task() got an unexpected keyword argument 'train_mode'

----------------------------------------------------------------------
Ran 52 tests in 0.022s

FAILED (errors=37)
```
the error is a bit longer, but I think you can guess what's going on. 
I have tried with both python 2.7 and python 3.6, and with both Mac OS and Ubuntu OS. 

Thanks in advance

Andrea

**Comment by germank** [comment]
Thanks for the report Andrea! This should be fixed now, so I'm closing the issue. Please, feel free to reopen if you are still having problems.

**Comment by andreamad8** [comment]
Partially solved. Sorry I haven't sent you all the error trace. I still have 13 errors:

```
EEEEEEEEEEEEE
======================================================================
ERROR: src.core.tests.test_channels (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.core.tests.test_channels
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/samurai/Documents/HKUST/Dialogue/CommAI-env/src/core/tests/test_channels.py", line 13, in <module>
    import core.serializer as serializer
ModuleNotFoundError: No module named 'core'


======================================================================
ERROR: src.core.tests.test_environment (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.core.tests.test_environment
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/samurai/Documents/HKUST/Dialogue/CommAI-env/src/core/tests/test_environment.py", line 13, in <module>
    import core.task as task
ModuleNotFoundError: No module named 'core'


======================================================================
ERROR: src.core.tests.test_events (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.core.tests.test_events
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/samurai/Documents/HKUST/Dialogue/CommAI-env/src/core/tests/test_events.py", line 13, in <module>
    import core.events as events
ModuleNotFoundError: No module named 'core'


======================================================================
ERROR: src.core.tests.test_serializer (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.core.tests.test_serializer
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/samurai/Documents/HKUST/Dialogue/CommAI-env/src/core/tests/test_serializer.py", line 14, in <module>
    from core import serializer
ModuleNotFoundError: No module named 'core'


======================================================================
ERROR: src.core.tests.test_session (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.core.tests.test_session
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/samurai/Documents/HKUST/Dialogue/CommAI-env/src/core/tests/test_session.py", line 13, in <module>
    import core.task as task
ModuleNotFoundError: No module named 'core'


======================================================================
ERROR: src.core.tests.test_task (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.core.tests.test_task
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/samurai/Documents/HKUST/Dialogue/CommAI-env/src/core/tests/test_task.py", line 13, in <module>
    import core.task as task
ModuleNotFoundError: No module named 'core'


======================================================================
ERROR: src.learners (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.learners
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/samurai/Documents/HKUST/Dialogue/CommAI-env/src/learners/__init__.py", line 19, in <module>
    __import__('learners.' + m)
ModuleNotFoundError: No module named 'learners'


======================================================================
ERROR: src.tasks.competition.tests.test_base (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.tasks.competition.tests.test_base
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/samurai/Documents/HKUST/Dialogue/CommAI-env/src/tasks/competition/tests/test_base.py", line 13, in <module>
    import tasks.competition.base as base
ModuleNotFoundError: No module named 'tasks'


======================================================================
ERROR: src.tasks.competition.tests.test_navigation (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.tasks.competition.tests.test_navigation
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/samurai/Documents/HKUST/Dialogue/CommAI-env/src/tasks/competition/tests/test_navigation.py", line 13, in <module>
    from worlds.grid_world import GridWorld
ModuleNotFoundError: No module named 'worlds'


======================================================================
ERROR: src.tasks.competition.tests.test_objects_properties (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.tasks.competition.tests.test_objects_properties
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/samurai/Documents/HKUST/Dialogue/CommAI-env/src/tasks/competition/tests/test_objects_properties.py", line 13, in <module>
    import tasks.competition.messages as msg
ModuleNotFoundError: No module named 'tasks'


======================================================================
ERROR: src.tasks.competition.tests.test_repetition (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.tasks.competition.tests.test_repetition
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/samurai/Documents/HKUST/Dialogue/CommAI-env/src/tasks/competition/tests/test_repetition.py", line 13, in <module>
    import tasks.competition.repetition as repetition
ModuleNotFoundError: No module named 'tasks'


======================================================================
ERROR: src.tasks.micro.tests.test_nano (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.tasks.micro.tests.test_nano
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/samurai/Documents/HKUST/Dialogue/CommAI-env/src/tasks/micro/tests/test_nano.py", line 13, in <module>
    import tasks.micro.nano as nano
ModuleNotFoundError: No module named 'tasks'


======================================================================
ERROR: src.tasks.micro.tests.test_small_comp (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.tasks.micro.tests.test_small_comp
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/samurai/Documents/HKUST/Dialogue/CommAI-env/src/tasks/micro/tests/test_small_comp.py", line 6, in <module>
    import tasks.micro.small_comp as small_comp
ModuleNotFoundError: No module named 'tasks'


----------------------------------------------------------------------
Ran 13 tests in 0.002s

FAILED (errors=13)
```

sorry to disturb you, and thank you for your fast reply

**Comment by andreamad8** [comment]
Right. My mistake sorry. 

Thanks again for the support 👍

**Comment by andreamad8** [comment]
I still have a little problem when I am running one of the example learner:

```
 python3 run.py -l learners.sample_learners.SampleRepeatingLearner -v ConsoleView tasks_config.sample.json
Traceback (most recent call last):
  File "run.py", line 214, in <module>
    main()
  File "run.py", line 88, in main
    session.run()
  File "/Users/samurai/Documents/HKUST/Dialogue/CommAI-env/src/core/session.py", line 52, in run
    token, reward = self._env.next(token, test_mode=self._learner.test_mode)
AttributeError: 'SampleRepeatingLearner' object has no attribute 'test_mode'
```

I partially solve it by my self by removing `test_mode=self._learner.test_mode` from the attribute. But I am sure there is a way clearer solution for the issue. 

Andrea

**Comment by germank** [comment]
Actually, just add a test_mode=False attribute in the SampleRepeatingLearner (and in your Learner class, for that matter). Thanks for letting us know about that problem too, I'll land a fix soon.
